# Ultralytics YOLO üöÄ, AGPL-3.0 license
# EXP 11: Dual-Stream + Cross-Modal Spatial Attention (CBAM)
# Chi·∫øn thu·∫≠t: TƒÉng c∆∞·ªùng kh·∫£ nƒÉng ph√°t hi·ªán v·∫≠t th·ªÉ nh·ªè b·∫±ng Spatial Attention

# Parameters
nc: 4 # S·ªë l·ªõp
scales:
  custom: [1.00, 1.00, 1024]

backbone:
  # [from, repeats, module, args]
  - [-1, 1, InputContainer, []] # 0

  # === BRANCH 1: RGB (YOLOv11s) ===
  - [0, 1, Conv, [32, 3, 2]] # 1
  - [-1, 1, Conv, [64, 3, 2]] # 2
  - [-1, 1, C3k2, [128, False, 0.25]] # 3
  - [-1, 1, Conv, [128, 3, 2]] # 4
  - [-1, 1, C3k2, [256, False, 0.25]] # 5 (P3 RGB)
  - [-1, 1, Conv, [256, 3, 2]] # 6
  - [-1, 1, C3k2, [256, True, 0.25]] # 7 (P4 RGB)
  - [-1, 1, Conv, [512, 3, 2]] # 8
  - [-1, 1, C3k2, [512, True, 0.25]] # 9
  - [-1, 1, SPPF, [512, 5]] # 10 (P5 RGB)

  # === BRANCH 2: NIR (YOLOv11n) ===
  - [0, 1, Conv, [16, 3, 2]] # 11
  - [-1, 1, Conv, [32, 3, 2]] # 12
  - [-1, 1, C3k2, [64, False, 0.25]] # 13
  - [-1, 1, Conv, [64, 3, 2]] # 14
  - [-1, 1, C3k2, [128, False, 0.25]] # 15 (P3 NIR)
  - [-1, 1, Conv, [128, 3, 2]] # 16
  - [-1, 1, C3k2, [128, True, 0.25]] # 17 (P4 NIR)
  - [-1, 1, Conv, [256, 3, 2]] # 18
  - [-1, 1, C3k2, [256, True, 0.25]] # 19
  - [-1, 1, SPPF, [256, 5]] # 20 (P5 NIR)

head:
  # === CROSS-CBAM FUSION NECK ===

  # Fusion P3
  - [15, 1, Conv, [256, 1, 1]]
  - [[5, 21], 1, FusionCrossCBAM, []] # <--- Module new

  # Fusion P4
  - [17, 1, Conv, [256, 1, 1]]
  - [[7, 23], 1, FusionCrossCBAM, []] # <--- Module new

  # Fusion P5
  - [20, 1, Conv, [512, 1, 1]]
  - [[10, 25], 1, FusionCrossCBAM, []] # <--- Module n√™w

  # === HEAD (YOLOv11) ===
  - [26, 1, C3k2, [512, False]] # 27
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 28
  - [[-1, 24], 1, Concat, [1]] # 29
  - [-1, 1, C3k2, [256, False]] # 30
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 31
  - [[-1, 22], 1, Concat, [1]] # 32
  - [-1, 1, C3k2, [128, False]] # 33
  - [-1, 1, Conv, [128, 3, 2]] # 34
  - [[-1, 30], 1, Concat, [1]] # 35
  - [-1, 1, C3k2, [256, False]] # 36
  - [-1, 1, Conv, [256, 3, 2]] # 37
  - [[-1, 27], 1, Concat, [1]] # 38
  - [-1, 1, C3k2, [512, True]] # 39
  - [[33, 36, 39], 1, Detect, [nc]] # 40
